// Parse event/log data based on the 'erc20' ABI
//
// Code generated by "genabi"; DO NOT EDIT.
package erc20

import (
	"github.com/indexsupply/x/abi"
	"github.com/indexsupply/x/abi/schema"
	"math/big"
)

type Approval struct {
	item *abi.Item

	// Indexed:
	Owner   [20]byte
	Spender [20]byte
	// Un-indexed:
	Value *big.Int
}

func (x Approval) Done() {
	x.item.Done()
}

func decodeApproval(item *abi.Item) Approval {
	x := Approval{}
	x.Value = item.At(0).BigInt()
	return x
}

var (
	approvalSignature  = [32]byte{0x8c, 0x5b, 0xe1, 0xe5, 0xeb, 0xec, 0x7d, 0x5b, 0xd1, 0x4f, 0x71, 0x42, 0x7d, 0x1e, 0x84, 0xf3, 0xdd, 0x3, 0x14, 0xc0, 0xf7, 0xb2, 0x29, 0x1e, 0x5b, 0x20, 0xa, 0xc8, 0xc7, 0xc3, 0xb9, 0x25}
	approvalSchema     = schema.Parse("(uint256)")
	approvalNumIndexed = int(2)
)

// Event Signature:
//	Approval(address,address,uint256)
// Checks the first log topic against the signature hash:
//	8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925
//
// Copies indexed event inputs from the remaining topics
// into [Approval]
//
// Uses the the following abi schema to decode the un-indexed
// event inputs from the log's data field into [Approval]:
//	(uint256)
func MatchApproval(l abi.Log) (Approval, bool) {
	if len(l.Topics) > 0 && approvalSignature != l.Topics[0] {
		return Approval{}, false
	}
	if len(l.Topics[1:]) != approvalNumIndexed {
		return Approval{}, false
	}
	_, item := abi.Decode(l.Data, approvalSchema)
	res := decodeApproval(item)
	res.item = item
	res.Owner = abi.Bytes(l.Topics[1][:]).Address()
	res.Spender = abi.Bytes(l.Topics[2][:]).Address()
	return res, true
}

type Transfer struct {
	item *abi.Item

	// Indexed:
	From [20]byte
	To   [20]byte
	// Un-indexed:
	Value *big.Int
}

func (x Transfer) Done() {
	x.item.Done()
}

func decodeTransfer(item *abi.Item) Transfer {
	x := Transfer{}
	x.Value = item.At(0).BigInt()
	return x
}

var (
	transferSignature  = [32]byte{0xdd, 0xf2, 0x52, 0xad, 0x1b, 0xe2, 0xc8, 0x9b, 0x69, 0xc2, 0xb0, 0x68, 0xfc, 0x37, 0x8d, 0xaa, 0x95, 0x2b, 0xa7, 0xf1, 0x63, 0xc4, 0xa1, 0x16, 0x28, 0xf5, 0x5a, 0x4d, 0xf5, 0x23, 0xb3, 0xef}
	transferSchema     = schema.Parse("(uint256)")
	transferNumIndexed = int(2)
)

// Event Signature:
//	Transfer(address,address,uint256)
// Checks the first log topic against the signature hash:
//	ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
//
// Copies indexed event inputs from the remaining topics
// into [Transfer]
//
// Uses the the following abi schema to decode the un-indexed
// event inputs from the log's data field into [Transfer]:
//	(uint256)
func MatchTransfer(l abi.Log) (Transfer, bool) {
	if len(l.Topics) > 0 && transferSignature != l.Topics[0] {
		return Transfer{}, false
	}
	if len(l.Topics[1:]) != transferNumIndexed {
		return Transfer{}, false
	}
	_, item := abi.Decode(l.Data, transferSchema)
	res := decodeTransfer(item)
	res.item = item
	res.From = abi.Bytes(l.Topics[1][:]).Address()
	res.To = abi.Bytes(l.Topics[2][:]).Address()
	return res, true
}
